from .cumpa import (
    CUMPA_DIE,
    CUMPA_IDLE,
    CUMPA_JUMP,
    CUMPA_WALK_ANIMATION_1,
    CUMPA_WALK_ANIMATION_2,
    CUMPA_WALK_ANIMATION_3,
)
from .hijita import (
    HIJITA_DIE,
    HIJITA_IDLE,
    HIJITA_JUMP,
    HIJITA_WALK_ANIMATION_1,
    HIJITA_WALK_ANIMATION_2,
    HIJITA_WALK_ANIMATION_3,
)
from .pariente import (
    PARIENTE_DIE,
    PARIENTE_IDLE,
    PARIENTE_JUMP,
    PARIENTE_WALK_ANIMATION_1,
    PARIENTE_WALK_ANIMATION_2,
    PARIENTE_WALK_ANIMATION_3,
)

__all__ = [
    "CUMPA_IDLE",
    "CUMPA_JUMP",
    "CUMPA_DIE",
    "HIJITA_IDLE",
    "HIJITA_JUMP",
    "HIJITA_DIE",
    "PARIENTE_IDLE",
    "PARIENTE_JUMP",
    "PARIENTE_DIE",
    "CUMPA_WALK_ANIMATION_1",
    "CUMPA_WALK_ANIMATION_2",
    "CUMPA_WALK_ANIMATION_3",
    "HIJITA_WALK_ANIMATION_1",
    "HIJITA_WALK_ANIMATION_2",
    "HIJITA_WALK_ANIMATION_3",
    "PARIENTE_WALK_ANIMATION_1",
    "PARIENTE_WALK_ANIMATION_2",
    "PARIENTE_WALK_ANIMATION_3",
]
