from .create_images import create_image
from src.utils.constants import GENERAL_SIZE, BIG_SIZE
from src.utils.directories import CUMPA_LVL_1_BRAKE_DIR, CUMPA_LVL_1_DEFAULT_DIR, CUMPA_LVL_1_DIED_DIR, CUMPA_LVL_1_DOWN_BACK_DIR, CUMPA_LVL_1_DOWN_FRONT_DIR, CUMPA_LVL_1_JUMP_DIR, CUMPA_LVL_1_WALKING_BACK_DIR, CUMPA_LVL_1_WALKING_FRONT_DIR, CUMPA_LVL_2_DEFAULT_DIR, CUMPA_LVL_2_BRAKE_DIR, CUMPA_LVL_2_DUCK_DIR, CUMPA_LVL_2_DOWN_FRONT_DIR, CUMPA_LVL_2_DOWN_BACK_DIR, CUMPA_LVL_2_JUMP_DIR, CUMPA_LVL_2_WALKING_FRONT_DIR, CUMPA_LVL_2_WALKING_BACK_DIR, CUMPA_LVL_3_DEFAULT_DIR, CUMPA_LVL_3_BRAKE_DIR, CUMPA_LVL_3_DUCK_DIR, CUMPA_LVL_3_DOWN_FRONT_DIR, CUMPA_LVL_3_DOWN_BACK_DIR, CUMPA_LVL_3_JUMP_DIR, CUMPA_LVL_3_WALKING_FRONT_DIR, CUMPA_LVL_3_WALKING_BACK_DIR, CUMPA_LVL_4_1_BRAKE_DIR, CUMPA_LVL_4_1_DEFAULT_DIR, CUMPA_LVL_4_1_DIED_DIR, CUMPA_LVL_4_1_DOWN_BACK_DIR, CUMPA_LVL_4_1_DOWN_FRONT_DIR, CUMPA_LVL_4_1_JUMP_DIR, CUMPA_LVL_4_1_WALKING_BACK_DIR, CUMPA_LVL_4_1_WALKING_FRONT_DIR, CUMPA_LVL_4_2_DEFAULT_DIR, CUMPA_LVL_4_2_BRAKE_DIR, CUMPA_LVL_4_2_DUCK_DIR, CUMPA_LVL_4_2_DOWN_FRONT_DIR, CUMPA_LVL_4_2_DOWN_BACK_DIR, CUMPA_LVL_4_2_JUMP_DIR, CUMPA_LVL_4_2_WALKING_FRONT_DIR, CUMPA_LVL_4_2_WALKING_BACK_DIR

# ==== LEVEL 1 ====

# Default
CUMPA_LVL_1_FRONT = create_image(CUMPA_LVL_1_DEFAULT_DIR + "front.png", GENERAL_SIZE)

CUMPA_LVL_1_BACK = create_image(CUMPA_LVL_1_DEFAULT_DIR + "back.png", GENERAL_SIZE)

# Brake
CUMPA_LVL_1_BRAKE_FRONT = create_image(CUMPA_LVL_1_BRAKE_DIR + "front.png", GENERAL_SIZE)

CUMPA_LVL_1_BRAKE_BACK = create_image(CUMPA_LVL_1_BRAKE_DIR + "back.png", GENERAL_SIZE)

# Died
CUMPA_LVL_1_DIED = create_image(CUMPA_LVL_1_DIED_DIR + "died.png", GENERAL_SIZE)

# Down
# front
CUMPA_LVL_1_DOWN_1_FRONT = create_image(CUMPA_LVL_1_DOWN_FRONT_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_1_DOWN_2_FRONT = create_image(CUMPA_LVL_1_DOWN_FRONT_DIR + "2.png", GENERAL_SIZE)

# back
CUMPA_LVL_1_DOWN_1_BACK = create_image(CUMPA_LVL_1_DOWN_BACK_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_1_DOWN_2_BACK = create_image(CUMPA_LVL_1_DOWN_BACK_DIR + "2.png", GENERAL_SIZE)

# Jump
CUMPA_LVL_1_JUMP_FRONT = create_image(CUMPA_LVL_1_JUMP_DIR + "front.png", GENERAL_SIZE)

CUMPA_LVL_1_JUMP_BACK = create_image(CUMPA_LVL_1_JUMP_DIR + "back.png", GENERAL_SIZE)

# Walking
# front
CUMPA_LVL_1_WALKING_1_FRONT = create_image(CUMPA_LVL_1_WALKING_FRONT_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_1_WALKING_2_FRONT = create_image(CUMPA_LVL_1_WALKING_FRONT_DIR + "2.png", GENERAL_SIZE)

CUMPA_LVL_1_WALKING_3_FRONT = create_image(CUMPA_LVL_1_WALKING_FRONT_DIR + "3.png", GENERAL_SIZE)

# back
CUMPA_LVL_1_WALKING_1_BACK = create_image(CUMPA_LVL_1_WALKING_BACK_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_1_WALKING_2_BACK = create_image(CUMPA_LVL_1_WALKING_BACK_DIR + "2.png", GENERAL_SIZE)

CUMPA_LVL_1_WALKING_3_BACK = create_image(CUMPA_LVL_1_WALKING_BACK_DIR + "3.png", GENERAL_SIZE)

# ==== LEVEL 2 ====

# Default
CUMPA_LVL_2_FRONT = create_image(CUMPA_LVL_2_DEFAULT_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_2_BACK = create_image(CUMPA_LVL_2_DEFAULT_DIR + "back.png", BIG_SIZE)

# Brake
CUMPA_LVL_2_BRAKE_FRONT = create_image(CUMPA_LVL_2_BRAKE_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_2_BRAKE_BACK = create_image(CUMPA_LVL_2_BRAKE_DIR + "back.png", BIG_SIZE)

# Duck
CUMPA_LVL_2_DUCK_FRONT = create_image(CUMPA_LVL_2_DUCK_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_2_DUCK_BACK = create_image(CUMPA_LVL_2_DUCK_DIR + "back.png", BIG_SIZE)

# Down
# front
CUMPA_LVL_2_DOWN_1_FRONT = create_image(CUMPA_LVL_2_DOWN_FRONT_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_2_DOWN_2_FRONT = create_image(CUMPA_LVL_2_DOWN_FRONT_DIR + "2.png", BIG_SIZE)

# back
CUMPA_LVL_2_DOWN_1_BACK = create_image(CUMPA_LVL_2_DOWN_BACK_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_2_DOWN_2_BACK = create_image(CUMPA_LVL_2_DOWN_BACK_DIR + "2.png", BIG_SIZE)

# Jump
CUMPA_LVL_2_JUMP_FRONT = create_image(CUMPA_LVL_2_JUMP_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_2_JUMP_BACK = create_image(CUMPA_LVL_2_JUMP_DIR + "back.png", BIG_SIZE)

# Walking
# front
CUMPA_LVL_2_WALKING_1_FRONT = create_image(CUMPA_LVL_2_WALKING_FRONT_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_2_WALKING_2_FRONT = create_image(CUMPA_LVL_2_WALKING_FRONT_DIR + "2.png", BIG_SIZE)

CUMPA_LVL_2_WALKING_3_FRONT = create_image(CUMPA_LVL_2_WALKING_FRONT_DIR + "3.png", BIG_SIZE)

# back
CUMPA_LVL_2_WALKING_1_BACK = create_image(CUMPA_LVL_2_WALKING_BACK_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_2_WALKING_2_BACK = create_image(CUMPA_LVL_2_WALKING_BACK_DIR + "2.png", BIG_SIZE)

CUMPA_LVL_2_WALKING_3_BACK = create_image(CUMPA_LVL_2_WALKING_BACK_DIR + "3.png", BIG_SIZE)

# ==== LEVEL 3 ====

# Default
CUMPA_LVL_3_FRONT = create_image(CUMPA_LVL_3_DEFAULT_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_3_BACK = create_image(CUMPA_LVL_3_DEFAULT_DIR + "back.png", BIG_SIZE)

# Brake
CUMPA_LVL_3_BRAKE_FRONT = create_image(CUMPA_LVL_3_BRAKE_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_3_BRAKE_BACK = create_image(CUMPA_LVL_3_BRAKE_DIR + "back.png", BIG_SIZE)

# Duck
CUMPA_LVL_3_DUCK_FRONT = create_image(CUMPA_LVL_3_DUCK_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_3_DUCK_BACK = create_image(CUMPA_LVL_3_DUCK_DIR + "back.png", BIG_SIZE)

# Down
# front
CUMPA_LVL_3_DOWN_1_FRONT = create_image(CUMPA_LVL_3_DOWN_FRONT_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_3_DOWN_2_FRONT = create_image(CUMPA_LVL_3_DOWN_FRONT_DIR + "2.png", BIG_SIZE)

# back
CUMPA_LVL_3_DOWN_1_BACK = create_image(CUMPA_LVL_3_DOWN_BACK_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_3_DOWN_2_BACK = create_image(CUMPA_LVL_3_DOWN_BACK_DIR + "2.png", BIG_SIZE)

# Jump
CUMPA_LVL_3_JUMP_FRONT = create_image(CUMPA_LVL_3_JUMP_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_3_JUMP_BACK = create_image(CUMPA_LVL_3_JUMP_DIR + "back.png", BIG_SIZE)

# Walking
# front
CUMPA_LVL_3_WALKING_1_FRONT = create_image(CUMPA_LVL_3_WALKING_FRONT_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_3_WALKING_2_FRONT = create_image(CUMPA_LVL_3_WALKING_FRONT_DIR + "2.png", BIG_SIZE)

CUMPA_LVL_3_WALKING_3_FRONT = create_image(CUMPA_LVL_3_WALKING_FRONT_DIR + "3.png", BIG_SIZE)

# back
CUMPA_LVL_3_WALKING_1_BACK = create_image(CUMPA_LVL_3_WALKING_BACK_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_3_WALKING_2_BACK = create_image(CUMPA_LVL_3_WALKING_BACK_DIR + "2.png", BIG_SIZE)

CUMPA_LVL_3_WALKING_3_BACK = create_image(CUMPA_LVL_3_WALKING_BACK_DIR + "3.png", BIG_SIZE)

# ==== LEVEL 4 ====

# == Level 1

# Default
CUMPA_LVL_4_1_FRONT = create_image(CUMPA_LVL_4_1_DEFAULT_DIR + "front.png", GENERAL_SIZE)

CUMPA_LVL_4_1_BACK = create_image(CUMPA_LVL_4_1_DEFAULT_DIR + "back.png", GENERAL_SIZE)

# Brake
CUMPA_LVL_4_1_BRAKE_FRONT = create_image(CUMPA_LVL_4_1_BRAKE_DIR + "front.png", GENERAL_SIZE)

CUMPA_LVL_4_1_BRAKE_BACK = create_image(CUMPA_LVL_4_1_BRAKE_DIR + "back.png", GENERAL_SIZE)

# Died
CUMPA_LVL_4_1_DIED = create_image(CUMPA_LVL_4_1_DIED_DIR + "died.png", GENERAL_SIZE)

# Down
# front
CUMPA_LVL_4_1_DOWN_1_FRONT = create_image(CUMPA_LVL_4_1_DOWN_FRONT_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_4_1_DOWN_2_FRONT = create_image(CUMPA_LVL_4_1_DOWN_FRONT_DIR + "2.png", GENERAL_SIZE)

# back
CUMPA_LVL_4_1_DOWN_1_BACK = create_image(CUMPA_LVL_4_1_DOWN_BACK_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_4_1_DOWN_2_BACK = create_image(CUMPA_LVL_4_1_DOWN_BACK_DIR + "2.png", GENERAL_SIZE)

# Jump
CUMPA_LVL_4_1_JUMP_FRONT = create_image(CUMPA_LVL_4_1_JUMP_DIR + "front.png", GENERAL_SIZE)

CUMPA_LVL_4_1_JUMP_BACK = create_image(CUMPA_LVL_4_1_JUMP_DIR + "back.png", GENERAL_SIZE)

# Walking
# front
CUMPA_LVL_4_1_WALKING_1_FRONT = create_image(CUMPA_LVL_4_1_WALKING_FRONT_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_4_1_WALKING_2_FRONT = create_image(CUMPA_LVL_4_1_WALKING_FRONT_DIR + "2.png", GENERAL_SIZE)

CUMPA_LVL_4_1_WALKING_3_FRONT = create_image(CUMPA_LVL_4_1_WALKING_FRONT_DIR + "3.png", GENERAL_SIZE)

# back
CUMPA_LVL_4_1_WALKING_1_BACK = create_image(CUMPA_LVL_4_1_WALKING_BACK_DIR + "1.png", GENERAL_SIZE)

CUMPA_LVL_4_1_WALKING_2_BACK = create_image(CUMPA_LVL_4_1_WALKING_BACK_DIR + "2.png", GENERAL_SIZE)

CUMPA_LVL_4_1_WALKING_3_BACK = create_image(CUMPA_LVL_4_1_WALKING_BACK_DIR + "3.png", GENERAL_SIZE)

# == Level 2

# Default
CUMPA_LVL_4_2_FRONT = create_image(CUMPA_LVL_4_2_DEFAULT_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_4_2_BACK = create_image(CUMPA_LVL_4_2_DEFAULT_DIR + "back.png", BIG_SIZE)

# Brake
CUMPA_LVL_4_2_BRAKE_FRONT = create_image(CUMPA_LVL_4_2_BRAKE_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_4_2_BRAKE_BACK = create_image(CUMPA_LVL_4_2_BRAKE_DIR + "back.png", BIG_SIZE)

# Duck
CUMPA_LVL_4_2_DUCK_FRONT = create_image(CUMPA_LVL_4_2_DUCK_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_4_2_DUCK_BACK = create_image(CUMPA_LVL_4_2_DUCK_DIR + "back.png", BIG_SIZE)

# Down
# front
CUMPA_LVL_4_2_DOWN_1_FRONT = create_image(CUMPA_LVL_4_2_DOWN_FRONT_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_4_2_DOWN_2_FRONT = create_image(CUMPA_LVL_4_2_DOWN_FRONT_DIR + "2.png", BIG_SIZE)

# back
CUMPA_LVL_4_2_DOWN_1_BACK = create_image(CUMPA_LVL_4_2_DOWN_BACK_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_4_2_DOWN_2_BACK = create_image(CUMPA_LVL_4_2_DOWN_BACK_DIR + "2.png", BIG_SIZE)

# Jump
CUMPA_LVL_4_2_JUMP_FRONT = create_image(CUMPA_LVL_4_2_JUMP_DIR + "front.png", BIG_SIZE)

CUMPA_LVL_4_2_JUMP_BACK = create_image(CUMPA_LVL_4_2_JUMP_DIR + "back.png", BIG_SIZE)

# Walking
# front
CUMPA_LVL_4_2_WALKING_1_FRONT = create_image(CUMPA_LVL_4_2_WALKING_FRONT_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_4_2_WALKING_2_FRONT = create_image(CUMPA_LVL_4_2_WALKING_FRONT_DIR + "2.png", BIG_SIZE)

CUMPA_LVL_4_2_WALKING_3_FRONT = create_image(CUMPA_LVL_4_2_WALKING_FRONT_DIR + "3.png", BIG_SIZE)

# back
CUMPA_LVL_4_2_WALKING_1_BACK = create_image(CUMPA_LVL_4_2_WALKING_BACK_DIR + "1.png", BIG_SIZE)

CUMPA_LVL_4_2_WALKING_2_BACK = create_image(CUMPA_LVL_4_2_WALKING_BACK_DIR + "2.png", BIG_SIZE)

CUMPA_LVL_4_2_WALKING_3_BACK = create_image(CUMPA_LVL_4_2_WALKING_BACK_DIR + "3.png", BIG_SIZE)
