from src.utils.assets.players.create_images import create_image
from src.utils.constants import PLAYER_SIZE
from src.utils.directories import HIJITA_LVL_1_BRAKE_DIR, HIJITA_LVL_1_DEFAULT_DIR, HIJITA_LVL_1_DIED_DIR, HIJITA_LVL_1_DOWN_BACK_DIR, HIJITA_LVL_1_DOWN_FRONT_DIR, HIJITA_LVL_1_JUMP_DIR, HIJITA_LVL_1_WALKING_BACK_DIR, HIJITA_LVL_1_WALKING_FRONT_DIR, HIJITA_LVL_2_DEFAULT_DIR, HIJITA_LVL_2_BRAKE_DIR, HIJITA_LVL_2_DUCK_DIR, HIJITA_LVL_2_DOWN_FRONT_DIR, HIJITA_LVL_2_DOWN_BACK_DIR, HIJITA_LVL_2_JUMP_DIR, HIJITA_LVL_2_WALKING_FRONT_DIR, HIJITA_LVL_2_WALKING_BACK_DIR, HIJITA_LVL_3_DEFAULT_DIR, HIJITA_LVL_3_BRAKE_DIR, HIJITA_LVL_3_DUCK_DIR, HIJITA_LVL_3_DOWN_FRONT_DIR, HIJITA_LVL_3_DOWN_BACK_DIR, HIJITA_LVL_3_JUMP_DIR, HIJITA_LVL_3_WALKING_FRONT_DIR, HIJITA_LVL_3_WALKING_BACK_DIR, HIJITA_LVL_4_1_BRAKE_DIR, HIJITA_LVL_4_1_DEFAULT_DIR, HIJITA_LVL_4_1_DIED_DIR, HIJITA_LVL_4_1_DOWN_BACK_DIR, HIJITA_LVL_4_1_DOWN_FRONT_DIR, HIJITA_LVL_4_1_JUMP_DIR, HIJITA_LVL_4_1_WALKING_BACK_DIR, HIJITA_LVL_4_1_WALKING_FRONT_DIR, HIJITA_LVL_4_2_DEFAULT_DIR, HIJITA_LVL_4_2_BRAKE_DIR, HIJITA_LVL_4_2_DUCK_DIR, HIJITA_LVL_4_2_DOWN_FRONT_DIR, HIJITA_LVL_4_2_DOWN_BACK_DIR, HIJITA_LVL_4_2_JUMP_DIR, HIJITA_LVL_4_2_WALKING_FRONT_DIR, HIJITA_LVL_4_2_WALKING_BACK_DIR

# ==== LEVEL 1 ====

# Default
HIJITA_LVL_1_FRONT = create_image(HIJITA_LVL_1_DEFAULT_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_1_BACK = create_image(HIJITA_LVL_1_DEFAULT_DIR + "back.png", PLAYER_SIZE)

# Brake
HIJITA_LVL_1_BRAKE_FRONT = create_image(HIJITA_LVL_1_BRAKE_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_1_BRAKE_BACK = create_image(HIJITA_LVL_1_BRAKE_DIR + "back.png", PLAYER_SIZE)

# Died
HIJITA_LVL_1_DIED = create_image(HIJITA_LVL_1_DIED_DIR + "died.png", PLAYER_SIZE)

# Down
# front
HIJITA_LVL_1_DOWN_1_FRONT = create_image(HIJITA_LVL_1_DOWN_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_1_DOWN_2_FRONT = create_image(HIJITA_LVL_1_DOWN_FRONT_DIR + "2.png", PLAYER_SIZE)

# back
HIJITA_LVL_1_DOWN_1_BACK = create_image(HIJITA_LVL_1_DOWN_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_1_DOWN_2_BACK = create_image(HIJITA_LVL_1_DOWN_BACK_DIR + "2.png", PLAYER_SIZE)

# Jump
HIJITA_LVL_1_JUMP_FRONT = create_image(HIJITA_LVL_1_JUMP_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_1_JUMP_BACK = create_image(HIJITA_LVL_1_JUMP_DIR + "back.png", PLAYER_SIZE)

# Walking
# front
HIJITA_LVL_1_WALKING_1_FRONT = create_image(HIJITA_LVL_1_WALKING_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_1_WALKING_2_FRONT = create_image(HIJITA_LVL_1_WALKING_FRONT_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_1_WALKING_3_FRONT = create_image(HIJITA_LVL_1_WALKING_FRONT_DIR + "3.png", PLAYER_SIZE)

# back
HIJITA_LVL_1_WALKING_1_BACK = create_image(HIJITA_LVL_1_WALKING_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_1_WALKING_2_BACK = create_image(HIJITA_LVL_1_WALKING_BACK_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_1_WALKING_3_BACK = create_image(HIJITA_LVL_1_WALKING_BACK_DIR + "3.png", PLAYER_SIZE)

# ==== LEVEL 2 ====

# Default
HIJITA_LVL_2_FRONT = create_image(HIJITA_LVL_2_DEFAULT_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_2_BACK = create_image(HIJITA_LVL_2_DEFAULT_DIR + "back.png", PLAYER_SIZE)

# Brake
HIJITA_LVL_2_BRAKE_FRONT = create_image(HIJITA_LVL_2_BRAKE_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_2_BRAKE_BACK = create_image(HIJITA_LVL_2_BRAKE_DIR + "back.png", PLAYER_SIZE)

# Duck
HIJITA_LVL_2_DUCK_FRONT = create_image(HIJITA_LVL_2_DUCK_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_2_DUCK_BACK = create_image(HIJITA_LVL_2_DUCK_DIR + "back.png", PLAYER_SIZE)

# Down
# front
HIJITA_LVL_2_DOWN_1_FRONT = create_image(HIJITA_LVL_2_DOWN_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_2_DOWN_2_FRONT = create_image(HIJITA_LVL_2_DOWN_FRONT_DIR + "2.png", PLAYER_SIZE)

# back
HIJITA_LVL_2_DOWN_1_BACK = create_image(HIJITA_LVL_2_DOWN_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_2_DOWN_2_BACK = create_image(HIJITA_LVL_2_DOWN_BACK_DIR + "2.png", PLAYER_SIZE)

# Jump
HIJITA_LVL_2_JUMP_FRONT = create_image(HIJITA_LVL_2_JUMP_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_2_JUMP_BACK = create_image(HIJITA_LVL_2_JUMP_DIR + "back.png", PLAYER_SIZE)

# Walking
# front
HIJITA_LVL_2_WALKING_1_FRONT = create_image(HIJITA_LVL_2_WALKING_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_2_WALKING_2_FRONT = create_image(HIJITA_LVL_2_WALKING_FRONT_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_2_WALKING_3_FRONT = create_image(HIJITA_LVL_2_WALKING_FRONT_DIR + "3.png", PLAYER_SIZE)

# back
HIJITA_LVL_2_WALKING_1_BACK = create_image(HIJITA_LVL_2_WALKING_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_2_WALKING_2_BACK = create_image(HIJITA_LVL_2_WALKING_BACK_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_2_WALKING_3_BACK = create_image(HIJITA_LVL_2_WALKING_BACK_DIR + "3.png", PLAYER_SIZE)

# ==== LEVEL 3 ====

# Default
HIJITA_LVL_3_FRONT = create_image(HIJITA_LVL_3_DEFAULT_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_3_BACK = create_image(HIJITA_LVL_3_DEFAULT_DIR + "back.png", PLAYER_SIZE)

# Brake
HIJITA_LVL_3_BRAKE_FRONT = create_image(HIJITA_LVL_3_BRAKE_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_3_BRAKE_BACK = create_image(HIJITA_LVL_3_BRAKE_DIR + "back.png", PLAYER_SIZE)

# Duck
HIJITA_LVL_3_DUCK_FRONT = create_image(HIJITA_LVL_3_DUCK_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_3_DUCK_BACK = create_image(HIJITA_LVL_3_DUCK_DIR + "back.png", PLAYER_SIZE)

# Down
# front
HIJITA_LVL_3_DOWN_1_FRONT = create_image(HIJITA_LVL_3_DOWN_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_3_DOWN_2_FRONT = create_image(HIJITA_LVL_3_DOWN_FRONT_DIR + "2.png", PLAYER_SIZE)

# back
HIJITA_LVL_3_DOWN_1_BACK = create_image(HIJITA_LVL_3_DOWN_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_3_DOWN_2_BACK = create_image(HIJITA_LVL_3_DOWN_BACK_DIR + "2.png", PLAYER_SIZE)

# Jump
HIJITA_LVL_3_JUMP_FRONT = create_image(HIJITA_LVL_3_JUMP_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_3_JUMP_BACK = create_image(HIJITA_LVL_3_JUMP_DIR + "back.png", PLAYER_SIZE)

# Walking
# front
HIJITA_LVL_3_WALKING_1_FRONT = create_image(HIJITA_LVL_3_WALKING_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_3_WALKING_2_FRONT = create_image(HIJITA_LVL_3_WALKING_FRONT_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_3_WALKING_3_FRONT = create_image(HIJITA_LVL_3_WALKING_FRONT_DIR + "3.png", PLAYER_SIZE)

# back
HIJITA_LVL_3_WALKING_1_BACK = create_image(HIJITA_LVL_3_WALKING_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_3_WALKING_2_BACK = create_image(HIJITA_LVL_3_WALKING_BACK_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_3_WALKING_3_BACK = create_image(HIJITA_LVL_3_WALKING_BACK_DIR + "3.png", PLAYER_SIZE)

# ==== LEVEL 4 ====

# == Level 1

# Default
HIJITA_LVL_4_1_FRONT = create_image(HIJITA_LVL_4_1_DEFAULT_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_1_BACK = create_image(HIJITA_LVL_4_1_DEFAULT_DIR + "back.png", PLAYER_SIZE)

# Brake
HIJITA_LVL_4_1_BRAKE_FRONT = create_image(HIJITA_LVL_4_1_BRAKE_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_1_BRAKE_BACK = create_image(HIJITA_LVL_4_1_BRAKE_DIR + "back.png", PLAYER_SIZE)

# Died
HIJITA_LVL_4_1_DIED = create_image(HIJITA_LVL_4_1_DIED_DIR + "died.png", PLAYER_SIZE)

# Down
# front
HIJITA_LVL_4_1_DOWN_1_FRONT = create_image(HIJITA_LVL_4_1_DOWN_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_1_DOWN_2_FRONT = create_image(HIJITA_LVL_4_1_DOWN_FRONT_DIR + "2.png", PLAYER_SIZE)

# back
HIJITA_LVL_4_1_DOWN_1_BACK = create_image(HIJITA_LVL_4_1_DOWN_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_1_DOWN_2_BACK = create_image(HIJITA_LVL_4_1_DOWN_BACK_DIR + "2.png", PLAYER_SIZE)

# Jump
HIJITA_LVL_4_1_JUMP_FRONT = create_image(HIJITA_LVL_4_1_JUMP_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_1_JUMP_BACK = create_image(HIJITA_LVL_4_1_JUMP_DIR + "back.png", PLAYER_SIZE)

# Walking
# front
HIJITA_LVL_4_1_WALKING_1_FRONT = create_image(HIJITA_LVL_4_1_WALKING_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_1_WALKING_2_FRONT = create_image(HIJITA_LVL_4_1_WALKING_FRONT_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_4_1_WALKING_3_FRONT = create_image(HIJITA_LVL_4_1_WALKING_FRONT_DIR + "3.png", PLAYER_SIZE)

# back
HIJITA_LVL_4_1_WALKING_1_BACK = create_image(HIJITA_LVL_4_1_WALKING_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_1_WALKING_2_BACK = create_image(HIJITA_LVL_4_1_WALKING_BACK_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_4_1_WALKING_3_BACK = create_image(HIJITA_LVL_4_1_WALKING_BACK_DIR + "3.png", PLAYER_SIZE)

# == Level 2

# Default
HIJITA_LVL_4_2_FRONT = create_image(HIJITA_LVL_4_2_DEFAULT_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_2_BACK = create_image(HIJITA_LVL_4_2_DEFAULT_DIR + "back.png", PLAYER_SIZE)

# Brake
HIJITA_LVL_4_2_BRAKE_FRONT = create_image(HIJITA_LVL_4_2_BRAKE_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_2_BRAKE_BACK = create_image(HIJITA_LVL_4_2_BRAKE_DIR + "back.png", PLAYER_SIZE)

# Duck
HIJITA_LVL_4_2_DUCK_FRONT = create_image(HIJITA_LVL_4_2_DUCK_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_2_DUCK_BACK = create_image(HIJITA_LVL_4_2_DUCK_DIR + "back.png", PLAYER_SIZE)

# Down
# front
HIJITA_LVL_4_2_DOWN_1_FRONT = create_image(HIJITA_LVL_4_2_DOWN_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_2_DOWN_2_FRONT = create_image(HIJITA_LVL_4_2_DOWN_FRONT_DIR + "2.png", PLAYER_SIZE)

# back
HIJITA_LVL_4_2_DOWN_1_BACK = create_image(HIJITA_LVL_4_2_DOWN_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_2_DOWN_2_BACK = create_image(HIJITA_LVL_4_2_DOWN_BACK_DIR + "2.png", PLAYER_SIZE)

# Jump
HIJITA_LVL_4_2_JUMP_FRONT = create_image(HIJITA_LVL_4_2_JUMP_DIR + "front.png", PLAYER_SIZE)

HIJITA_LVL_4_2_JUMP_BACK = create_image(HIJITA_LVL_4_2_JUMP_DIR + "back.png", PLAYER_SIZE)

# Walking
# front
HIJITA_LVL_4_2_WALKING_1_FRONT = create_image(HIJITA_LVL_4_2_WALKING_FRONT_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_2_WALKING_2_FRONT = create_image(HIJITA_LVL_4_2_WALKING_FRONT_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_4_2_WALKING_3_FRONT = create_image(HIJITA_LVL_4_2_WALKING_FRONT_DIR + "3.png", PLAYER_SIZE)

# back
HIJITA_LVL_4_2_WALKING_1_BACK = create_image(HIJITA_LVL_4_2_WALKING_BACK_DIR + "1.png", PLAYER_SIZE)

HIJITA_LVL_4_2_WALKING_2_BACK = create_image(HIJITA_LVL_4_2_WALKING_BACK_DIR + "2.png", PLAYER_SIZE)

HIJITA_LVL_4_2_WALKING_3_BACK = create_image(HIJITA_LVL_4_2_WALKING_BACK_DIR + "3.png", PLAYER_SIZE)
