from enum import Enum


class ElementSubType(Enum):
    # BLOCKS
    OVERWORLD_BLOCK = "OVERWORLD_BLOCK"
    UNDERGROUND_BLOCK = "UNDERGROUND_BLOCK"
    OVERWORLD_BRICK = "OVERWORLD_BRICK"
    OVERWORLD_BROKE_BRICK = "OVERWORLD_BROKE_BRICK"

    SMALL_BUSH = "SMALL_BUSH"
    MEDIUM_BUSH = "MEDIUM_BUSH"
    BIG_BUSH = "BIG_BUSH"
    DEFAULT_CASTLE = "DEFAULT_CASTLE"

    # CLOUDS
    SMALL_CLOUD = "SMALL_CLOUD"
    MEDIUM_CLOUD = "MEDIUM_CLOUD"
    BIG_CLOUD = "BIG_CLOUD"

    DEFAULT_FLAG = "DEFAULT_FLAG"

    DEFAULT_MOUNTAIN = "DEFAULT_MOUNTAIN"

    # PIPES
    # Head
    PIPE_HEAD = "PIPE_HEAD"

    # Body
    PIPE_BODY = "PIPE_BODY"

    # COINS
    COIN = "COIN"

    # MASTERY BLOCK
    MASTERY_BLOCK = "MASTERY_BLOCK"
