from enum import Enum


class ElementSubType(Enum):
    OVERWORLD_BLOCK = "OVERWORLD_BLOCK"
    UNDERGROUND_BLOCK = "UNDERGROUND_BLOCK"
    SMALL_BUSH = "SMALL_BUSH"
    MEDIUM_BUSH = "MEDIUM_BUSH"
    BIG_BUSH = "BIG_BUSH"
    DEFAULT_CASTLE = "DEFAULT_CASTLE"
    SMALL_CLOUD = "SMALL_CLOUD"
    MEDIUM_CLOUD = "MEDIUM_CLOUD"
    BIG_CLOUD = "BIG_CLOUD"
    DEFAULT_COIN = "DEFAULT_COIN"
    DEFAULT_FLAG = "DEFAULT_FLAG"
    DEFAULT_MISTERY_BOX = "DEFAULT_MISTERY_BOX"
    DEFAULT_MOUNTAIN = "DEFAULT_MOUNTAIN"
    SMALL_PIPE = "SMALL_PIPE"
    MEDIUM_PIPE = "MEDIUM_PIPE"
    BIG_PIPE = "BIG_PIPE"
