# GAME CONSTANTS
TITLE = "Super Piton Bros"
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
FPS = 60.0

# INPUT CONSTANTS
DEFAULT_HORIZONTAL_AXIS_VALUE = 0.0
DEFAULT_VERTICAL_AXIS_VALUE = 0.0
DEFAULT_R_TWO_VALUE = -1.0
DEFAULT_MIN_SENSIBILITY = 0.2
DEFAULT_TRIGGER_SENSIBILITY = 0.4
DEFAULT_R_TWO_SENSIBILITY = 0.6

# UI CONSTANTS
FONT_SIZE = 24

# VIDEO CONSTANTS
BGR_FORMAT = "BGR"
VIDEO_SCREEN_POSITION = (0, 0)

# IMAGE CONSTANTS
INIT_IMAGE_INDEX = 0
ANIMATION_INTERVAL = 85

# PLAYER CONSTANTS
PLAYER_SIZE = (100, 100)
HERO_SPEED = 6
MAX_GRAVITY = 10
JUMP_VELOCITY = 30
DEAD_FALL_THRESHOLD = 25

# LEVELS CONSTANTS
TRANSITION_DURATION = 3000
TO_SECONDS = 1000

# SCALE GAME
COLLISION_WIDTH_SCALE = 0.95
SCALE = 1.2

# GENERAL SIZES
# 16 x 16 pixels
GENERAL_WIDTH = 60
GENERAL_HEIGHT = 60
GENERAL_SIZE = (60, 60)

# 32 x 32 pixels
BIG_SIZE = (120, 120)

# ICONS SIZE
ICONS_SIZE = (22.5, 22.5)

# COIN SIZE
COIN_SIZE = (33.75, 60)

# SCORE LIMIT
SCORE_LIMIT = 999_999
