# GAME CONSTANTS
TITLE = "Super Piton Bros"
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
FPS = 60

# INPUT CONSTANTS
DEFAULT_HORIZONTAL_AXIS_VALUE = 0.0
DEFAULT_VERTICAL_AXIS_VALUE = 0.0
DEFAULT_R_TWO_VALUE = -1.0
DEFAULT_MIN_SENSIBILITY = 0.2
DEFAULT_TRIGGER_SENSIBILITY = 0.4
DEFAULT_R_TWO_SENSIBILITY = 0.6

# UI CONSTANTS
FONT_SIZE = 30
HALF = 2

# VIDEO CONSTANTS
BGR_FORMAT = "BGR"
VIDEO_SCREEN_POSITION = (0, 0)
