# === Resources ===
RESOURCES_DIR = "resources/"

# == Levels ==
LEVELS_DIR = RESOURCES_DIR + "levels"

# === Assets ===
ASSETS_DIR = "assets/"

# == Fonts ==
FONTS_DIR = ASSETS_DIR + "fonts/"

# == Logos ==
LOGOS_DIR = ASSETS_DIR + "logo/"

# == Cinematics ==
CINEMATICS_DIR = ASSETS_DIR + "cinematics/"
FINAL_CINEMATIC_DIR = CINEMATICS_DIR + "final_cinematic/"

# == Elements ==
ELEMENTS_DIR = ASSETS_DIR + "elements/"

TOUCHABLE_ELEMENTS_DIR = ELEMENTS_DIR + "touchable/"
BLOCK_DIR = TOUCHABLE_ELEMENTS_DIR + "block/"
PIPE_DIR = TOUCHABLE_ELEMENTS_DIR + "pipe/"

NON_TOUCHABLE_ELEMENTS_DIR = ELEMENTS_DIR + "non_touchable/"
CLOUD_DIR = NON_TOUCHABLE_ELEMENTS_DIR + "cloud/"

# == SPRITES ==
SPRITES_DIR = ASSETS_DIR + "sprites/"

# == Sprites dirs ==
BLOCKS_DIR = SPRITES_DIR + "blocks/"
ENEMIES_DIR = SPRITES_DIR + "enemies/"
ICONS_DIR = SPRITES_DIR + "icons/"
PLAYERS_DIR = SPRITES_DIR + "players/"
POWER_UPS_DIR = SPRITES_DIR + "power_ups/"

# == Players ==

# == players names ==
PARIENTE_DIR = PLAYERS_DIR + "pariente/"
CUMPA_DIR = PLAYERS_DIR + "cumpa/"
HIJITA_DIR = PLAYERS_DIR + "hijita/"

# == player actions ==
DEFAULT_DIR = "default/"
WALKING_DIR = "walking/"
DOWN_DIR = "down/"
DIED_DIR = "died/"
JUMP_DIR = "jump/"
BRAKE_DIR = "brake/"
DUCK_DIR = "duck/"

# == player levels ==
LVL_1_DIR = "lvl_1/"
LVL_2_DIR = "lvl_2/"
LVL_3_DIR = "lvl_3/"
LVL_4_DIR = "lvl_4/"

# == cumpa ==
# == cumpa level 1 ==
CUMPA_LVL_1_DIR = CUMPA_DIR + LVL_1_DIR
CUMPA_LVL_1_DEFAULT_DIR = CUMPA_LVL_1_DIR + DEFAULT_DIR
CUMPA_LVL_1_BRAKE_DIR = CUMPA_LVL_1_DIR + BRAKE_DIR
CUMPA_LVL_1_DIED_DIR = CUMPA_LVL_1_DIR + DIED_DIR
CUMPA_LVL_1_DOWN_DIR = CUMPA_LVL_1_DIR + DOWN_DIR
CUMPA_LVL_1_JUMP_DIR = CUMPA_LVL_1_DIR + JUMP_DIR
CUMPA_LVL_1_WALKING_DIR = CUMPA_LVL_1_DIR + WALKING_DIR

# == cumpa level 2 ==
CUMPA_LVL_2_DIR = CUMPA_DIR + LVL_2_DIR
CUMPA_LVL_2_DEFAULT_DIR = CUMPA_LVL_2_DIR + DEFAULT_DIR
CUMPA_LVL_2_BRAKE_DIR = CUMPA_LVL_2_DIR + BRAKE_DIR
CUMPA_LVL_2_DUCK_DIR = CUMPA_LVL_2_DIR + DUCK_DIR
CUMPA_LVL_2_DOWN_DIR = CUMPA_LVL_2_DIR + DOWN_DIR
CUMPA_LVL_2_JUMP_DIR = CUMPA_LVL_2_DIR + JUMP_DIR
CUMPA_LVL_2_WALKING_DIR = CUMPA_LVL_2_DIR + WALKING_DIR

# == cumpa level 3 ==
CUMPA_LVL_3_DIR = CUMPA_DIR + LVL_3_DIR
CUMPA_LVL_3_DEFAULT_DIR = CUMPA_LVL_3_DIR + DEFAULT_DIR
CUMPA_LVL_3_BRAKE_DIR = CUMPA_LVL_3_DIR + BRAKE_DIR
CUMPA_LVL_3_DUCK_DIR = CUMPA_LVL_3_DIR + DUCK_DIR
CUMPA_LVL_3_DOWN_DIR = CUMPA_LVL_3_DIR + DOWN_DIR
CUMPA_LVL_3_JUMP_DIR = CUMPA_LVL_3_DIR + JUMP_DIR
CUMPA_LVL_3_WALKING_DIR = CUMPA_LVL_3_DIR + WALKING_DIR

# == cumpa level 4 ==

# == cumpa level 4_1 ==
CUMPA_LVL_4_1_DIR = CUMPA_DIR + LVL_4_DIR + LVL_1_DIR
CUMPA_LVL_4_1_DEFAULT_DIR = CUMPA_LVL_4_1_DIR + DEFAULT_DIR
CUMPA_LVL_4_1_BRAKE_DIR = CUMPA_LVL_4_1_DIR + BRAKE_DIR
CUMPA_LVL_4_1_DIED_DIR = CUMPA_LVL_4_1_DIR + DIED_DIR
CUMPA_LVL_4_1_DOWN_DIR = CUMPA_LVL_4_1_DIR + DOWN_DIR
CUMPA_LVL_4_1_JUMP_DIR = CUMPA_LVL_4_1_DIR + JUMP_DIR
CUMPA_LVL_4_1_WALKING_DIR = CUMPA_LVL_4_1_DIR + WALKING_DIR

# == cumpa level 2 ==
CUMPA_LVL_4_2_DIR = CUMPA_DIR + LVL_4_DIR + LVL_2_DIR
CUMPA_LVL_4_2_DEFAULT_DIR = CUMPA_LVL_4_2_DIR + DEFAULT_DIR
CUMPA_LVL_4_2_BRAKE_DIR = CUMPA_LVL_4_2_DIR + BRAKE_DIR
CUMPA_LVL_4_2_DUCK_DIR = CUMPA_LVL_4_2_DIR + DUCK_DIR
CUMPA_LVL_4_2_DOWN_DIR = CUMPA_LVL_4_2_DIR + DOWN_DIR
CUMPA_LVL_4_2_JUMP_DIR = CUMPA_LVL_4_2_DIR + JUMP_DIR
CUMPA_LVL_4_2_WALKING_DIR = CUMPA_LVL_4_2_DIR + WALKING_DIR

# == pariente ==
# == pariente level 1 ==
PARIENTE_LVL_1_DIR = PARIENTE_DIR + LVL_1_DIR
PARIENTE_LVL_1_DEFAULT_DIR = PARIENTE_LVL_1_DIR + DEFAULT_DIR
PARIENTE_LVL_1_BRAKE_DIR = PARIENTE_LVL_1_DIR + BRAKE_DIR
PARIENTE_LVL_1_DIED_DIR = PARIENTE_LVL_1_DIR + DIED_DIR
PARIENTE_LVL_1_DOWN_DIR = PARIENTE_LVL_1_DIR + DOWN_DIR
PARIENTE_LVL_1_JUMP_DIR = PARIENTE_LVL_1_DIR + JUMP_DIR
PARIENTE_LVL_1_WALKING_DIR = PARIENTE_LVL_1_DIR + WALKING_DIR

# == pariente level 2 ==
PARIENTE_LVL_2_DIR = PARIENTE_DIR + LVL_2_DIR
PARIENTE_LVL_2_DEFAULT_DIR = PARIENTE_LVL_2_DIR + DEFAULT_DIR
PARIENTE_LVL_2_BRAKE_DIR = PARIENTE_LVL_2_DIR + BRAKE_DIR
PARIENTE_LVL_2_DUCK_DIR = PARIENTE_LVL_2_DIR + DUCK_DIR
PARIENTE_LVL_2_DOWN_DIR = PARIENTE_LVL_2_DIR + DOWN_DIR
PARIENTE_LVL_2_JUMP_DIR = PARIENTE_LVL_2_DIR + JUMP_DIR
PARIENTE_LVL_2_WALKING_DIR = PARIENTE_LVL_2_DIR + WALKING_DIR

# == pariente level 3 ==
PARIENTE_LVL_3_DIR = PARIENTE_DIR + LVL_3_DIR
PARIENTE_LVL_3_DEFAULT_DIR = PARIENTE_LVL_3_DIR + DEFAULT_DIR
PARIENTE_LVL_3_BRAKE_DIR = PARIENTE_LVL_3_DIR + BRAKE_DIR
PARIENTE_LVL_3_DUCK_DIR = PARIENTE_LVL_3_DIR + DUCK_DIR
PARIENTE_LVL_3_DOWN_DIR = PARIENTE_LVL_3_DIR + DOWN_DIR
PARIENTE_LVL_3_JUMP_DIR = PARIENTE_LVL_3_DIR + JUMP_DIR
PARIENTE_LVL_3_WALKING_DIR = PARIENTE_LVL_3_DIR + WALKING_DIR

# == pariente level 4 ==

# == pariente level 4_1 ==
PARIENTE_LVL_4_1_DIR = PARIENTE_DIR + LVL_4_DIR + LVL_1_DIR
PARIENTE_LVL_4_1_DEFAULT_DIR = PARIENTE_LVL_4_1_DIR + DEFAULT_DIR
PARIENTE_LVL_4_1_BRAKE_DIR = PARIENTE_LVL_4_1_DIR + BRAKE_DIR
PARIENTE_LVL_4_1_DIED_DIR = PARIENTE_LVL_4_1_DIR + DIED_DIR
PARIENTE_LVL_4_1_DOWN_DIR = PARIENTE_LVL_4_1_DIR + DOWN_DIR
PARIENTE_LVL_4_1_JUMP_DIR = PARIENTE_LVL_4_1_DIR + JUMP_DIR
PARIENTE_LVL_4_1_WALKING_DIR = PARIENTE_LVL_4_1_DIR + WALKING_DIR

# == pariente level 2 ==
PARIENTE_LVL_4_2_DIR = PARIENTE_DIR + LVL_4_DIR + LVL_2_DIR
PARIENTE_LVL_4_2_DEFAULT_DIR = PARIENTE_LVL_4_2_DIR + DEFAULT_DIR
PARIENTE_LVL_4_2_BRAKE_DIR = PARIENTE_LVL_4_2_DIR + BRAKE_DIR
PARIENTE_LVL_4_2_DUCK_DIR = PARIENTE_LVL_4_2_DIR + DUCK_DIR
PARIENTE_LVL_4_2_DOWN_DIR = PARIENTE_LVL_4_2_DIR + DOWN_DIR
PARIENTE_LVL_4_2_JUMP_DIR = PARIENTE_LVL_4_2_DIR + JUMP_DIR
PARIENTE_LVL_4_2_WALKING_DIR = PARIENTE_LVL_4_2_DIR + WALKING_DIR

# == hijita ==
# == hijita level 1 ==
HIJITA_LVL_1_DIR = HIJITA_DIR + LVL_1_DIR
HIJITA_LVL_1_DEFAULT_DIR = HIJITA_LVL_1_DIR + DEFAULT_DIR
HIJITA_LVL_1_BRAKE_DIR = HIJITA_LVL_1_DIR + BRAKE_DIR
HIJITA_LVL_1_DIED_DIR = HIJITA_LVL_1_DIR + DIED_DIR
HIJITA_LVL_1_DOWN_DIR = HIJITA_LVL_1_DIR + DOWN_DIR
HIJITA_LVL_1_JUMP_DIR = HIJITA_LVL_1_DIR + JUMP_DIR
HIJITA_LVL_1_WALKING_DIR = HIJITA_LVL_1_DIR + WALKING_DIR

# == hijita level 2 ==
HIJITA_LVL_2_DIR = HIJITA_DIR + LVL_2_DIR
HIJITA_LVL_2_DEFAULT_DIR = HIJITA_LVL_2_DIR + DEFAULT_DIR
HIJITA_LVL_2_BRAKE_DIR = HIJITA_LVL_2_DIR + BRAKE_DIR
HIJITA_LVL_2_DUCK_DIR = HIJITA_LVL_2_DIR + DUCK_DIR
HIJITA_LVL_2_DOWN_DIR = HIJITA_LVL_2_DIR + DOWN_DIR
HIJITA_LVL_2_JUMP_DIR = HIJITA_LVL_2_DIR + JUMP_DIR
HIJITA_LVL_2_WALKING_DIR = HIJITA_LVL_2_DIR + WALKING_DIR

# == hijita level 3 ==
HIJITA_LVL_3_DIR = HIJITA_DIR + LVL_3_DIR
HIJITA_LVL_3_DEFAULT_DIR = HIJITA_LVL_3_DIR + DEFAULT_DIR
HIJITA_LVL_3_BRAKE_DIR = HIJITA_LVL_3_DIR + BRAKE_DIR
HIJITA_LVL_3_DUCK_DIR = HIJITA_LVL_3_DIR + DUCK_DIR
HIJITA_LVL_3_DOWN_DIR = HIJITA_LVL_3_DIR + DOWN_DIR
HIJITA_LVL_3_JUMP_DIR = HIJITA_LVL_3_DIR + JUMP_DIR
HIJITA_LVL_3_WALKING_DIR = HIJITA_LVL_3_DIR + WALKING_DIR

# == hijita level 4 ==

# == hijita level 4_1 ==
HIJITA_LVL_4_1_DIR = HIJITA_DIR + LVL_4_DIR + LVL_1_DIR
HIJITA_LVL_4_1_DEFAULT_DIR = HIJITA_LVL_4_1_DIR + DEFAULT_DIR
HIJITA_LVL_4_1_BRAKE_DIR = HIJITA_LVL_4_1_DIR + BRAKE_DIR
HIJITA_LVL_4_1_DIED_DIR = HIJITA_LVL_4_1_DIR + DIED_DIR
HIJITA_LVL_4_1_DOWN_DIR = HIJITA_LVL_4_1_DIR + DOWN_DIR
HIJITA_LVL_4_1_JUMP_DIR = HIJITA_LVL_4_1_DIR + JUMP_DIR
HIJITA_LVL_4_1_WALKING_DIR = HIJITA_LVL_4_1_DIR + WALKING_DIR

# == hijita level 2 ==
HIJITA_LVL_4_2_DIR = HIJITA_DIR + LVL_4_DIR + LVL_2_DIR
HIJITA_LVL_4_2_DEFAULT_DIR = HIJITA_LVL_4_2_DIR + DEFAULT_DIR
HIJITA_LVL_4_2_BRAKE_DIR = HIJITA_LVL_4_2_DIR + BRAKE_DIR
HIJITA_LVL_4_2_DUCK_DIR = HIJITA_LVL_4_2_DIR + DUCK_DIR
HIJITA_LVL_4_2_DOWN_DIR = HIJITA_LVL_4_2_DIR + DOWN_DIR
HIJITA_LVL_4_2_JUMP_DIR = HIJITA_LVL_4_2_DIR + JUMP_DIR
HIJITA_LVL_4_2_WALKING_DIR = HIJITA_LVL_4_2_DIR + WALKING_DIR
