from typing import Dict, List

from pygame import Surface

from src.enums import (
    ElementSubType,
    ElementType,
    EnemyState,
    EnemyType,
    HeroLevel,
    HeroState,
    HeroType,
    PowerUpType,
)

from .assets import (
    ALCOHOL_CAIMAN,
    BIG_BUSH,
    BIG_CLOUD,
    BIG_MOUNTAIN,
    BIG_TREE,
    CASTLE,
    COCA_PLANT_1,
    COCA_PLANT_2,
    COIN_1,
    COIN_2,
    COIN_3,
    COIN_4,
    COIN_ICON_1,
    COIN_ICON_2,
    COIN_ICON_3,
    CUMPA_LVL_1,
    CUMPA_LVL_1_BRAKE,
    CUMPA_LVL_1_DIED,
    CUMPA_LVL_1_DOWN_1,
    CUMPA_LVL_1_DOWN_2,
    CUMPA_LVL_1_JUMP,
    CUMPA_LVL_1_WALKING_1,
    CUMPA_LVL_1_WALKING_2,
    CUMPA_LVL_1_WALKING_3,
    CUMPA_LVL_2,
    CUMPA_LVL_2_BRAKE,
    CUMPA_LVL_2_DOWN_1,
    CUMPA_LVL_2_DOWN_2,
    CUMPA_LVL_2_DUCK,
    CUMPA_LVL_2_JUMP,
    CUMPA_LVL_2_WALKING_1,
    CUMPA_LVL_2_WALKING_2,
    CUMPA_LVL_2_WALKING_3,
    CUMPA_LVL_3,
    CUMPA_LVL_3_BRAKE,
    CUMPA_LVL_3_DOWN_1,
    CUMPA_LVL_3_DOWN_2,
    CUMPA_LVL_3_DUCK,
    CUMPA_LVL_3_JUMP,
    CUMPA_LVL_3_WALKING_1,
    CUMPA_LVL_3_WALKING_2,
    CUMPA_LVL_3_WALKING_3,
    CUMPA_LVL_4_1,
    CUMPA_LVL_4_1_BRAKE,
    CUMPA_LVL_4_1_DIED,
    CUMPA_LVL_4_1_DOWN_1,
    CUMPA_LVL_4_1_DOWN_2,
    CUMPA_LVL_4_1_JUMP,
    CUMPA_LVL_4_1_WALKING_1,
    CUMPA_LVL_4_1_WALKING_2,
    CUMPA_LVL_4_1_WALKING_3,
    CUMPA_LVL_4_2,
    CUMPA_LVL_4_2_BRAKE,
    CUMPA_LVL_4_2_DOWN_1,
    CUMPA_LVL_4_2_DOWN_2,
    CUMPA_LVL_4_2_DUCK,
    CUMPA_LVL_4_2_JUMP,
    CUMPA_LVL_4_2_WALKING_1,
    CUMPA_LVL_4_2_WALKING_2,
    CUMPA_LVL_4_2_WALKING_3,
    EVOOMBA_DIED,
    EVOOMBA_WALKING_1,
    EVOOMBA_WALKING_2,
    FLAG_LIMITER,
    FLAG_PIPE,
    FLAG_SUPPORT,
    FLAG_WIN,
    HIJITA_LVL_1,
    HIJITA_LVL_1_BRAKE,
    HIJITA_LVL_1_DIED,
    HIJITA_LVL_1_DOWN_1,
    HIJITA_LVL_1_DOWN_2,
    HIJITA_LVL_1_JUMP,
    HIJITA_LVL_1_WALKING_1,
    HIJITA_LVL_1_WALKING_2,
    HIJITA_LVL_1_WALKING_3,
    HIJITA_LVL_2,
    HIJITA_LVL_2_BRAKE,
    HIJITA_LVL_2_DOWN_1,
    HIJITA_LVL_2_DOWN_2,
    HIJITA_LVL_2_DUCK,
    HIJITA_LVL_2_JUMP,
    HIJITA_LVL_2_WALKING_1,
    HIJITA_LVL_2_WALKING_2,
    HIJITA_LVL_2_WALKING_3,
    HIJITA_LVL_3,
    HIJITA_LVL_3_BRAKE,
    HIJITA_LVL_3_DOWN_1,
    HIJITA_LVL_3_DOWN_2,
    HIJITA_LVL_3_DUCK,
    HIJITA_LVL_3_JUMP,
    HIJITA_LVL_3_WALKING_1,
    HIJITA_LVL_3_WALKING_2,
    HIJITA_LVL_3_WALKING_3,
    HIJITA_LVL_4_1,
    HIJITA_LVL_4_1_BRAKE,
    HIJITA_LVL_4_1_DIED,
    HIJITA_LVL_4_1_DOWN_1,
    HIJITA_LVL_4_1_DOWN_2,
    HIJITA_LVL_4_1_JUMP,
    HIJITA_LVL_4_1_WALKING_1,
    HIJITA_LVL_4_1_WALKING_2,
    HIJITA_LVL_4_1_WALKING_3,
    HIJITA_LVL_4_2,
    HIJITA_LVL_4_2_BRAKE,
    HIJITA_LVL_4_2_DOWN_1,
    HIJITA_LVL_4_2_DOWN_2,
    HIJITA_LVL_4_2_DUCK,
    HIJITA_LVL_4_2_JUMP,
    HIJITA_LVL_4_2_WALKING_1,
    HIJITA_LVL_4_2_WALKING_2,
    HIJITA_LVL_4_2_WALKING_3,
    MASTERY_BLOCK_1,
    MASTERY_BLOCK_2,
    MASTERY_BLOCK_3,
    MEDIUM_BUSH,
    MEDIUM_CLOUD,
    MEDIUM_MOUNTAIN,
    MEDIUM_TREE,
    OVERWORLD_BLOCK,
    OVERWORLD_TERRAIN_BLOCK,
    PARIENTE_LVL_1,
    PARIENTE_LVL_1_BRAKE,
    PARIENTE_LVL_1_DIED,
    PARIENTE_LVL_1_DOWN_1,
    PARIENTE_LVL_1_DOWN_2,
    PARIENTE_LVL_1_JUMP,
    PARIENTE_LVL_1_WALKING_1,
    PARIENTE_LVL_1_WALKING_2,
    PARIENTE_LVL_1_WALKING_3,
    PARIENTE_LVL_2,
    PARIENTE_LVL_2_BRAKE,
    PARIENTE_LVL_2_DOWN_1,
    PARIENTE_LVL_2_DOWN_2,
    PARIENTE_LVL_2_DUCK,
    PARIENTE_LVL_2_JUMP,
    PARIENTE_LVL_2_WALKING_1,
    PARIENTE_LVL_2_WALKING_2,
    PARIENTE_LVL_2_WALKING_3,
    PARIENTE_LVL_3,
    PARIENTE_LVL_3_BRAKE,
    PARIENTE_LVL_3_DOWN_1,
    PARIENTE_LVL_3_DOWN_2,
    PARIENTE_LVL_3_DUCK,
    PARIENTE_LVL_3_JUMP,
    PARIENTE_LVL_3_WALKING_1,
    PARIENTE_LVL_3_WALKING_2,
    PARIENTE_LVL_3_WALKING_3,
    PARIENTE_LVL_4_1,
    PARIENTE_LVL_4_1_BRAKE,
    PARIENTE_LVL_4_1_DIED,
    PARIENTE_LVL_4_1_DOWN_1,
    PARIENTE_LVL_4_1_DOWN_2,
    PARIENTE_LVL_4_1_JUMP,
    PARIENTE_LVL_4_1_WALKING_1,
    PARIENTE_LVL_4_1_WALKING_2,
    PARIENTE_LVL_4_1_WALKING_3,
    PARIENTE_LVL_4_2,
    PARIENTE_LVL_4_2_BRAKE,
    PARIENTE_LVL_4_2_DOWN_1,
    PARIENTE_LVL_4_2_DOWN_2,
    PARIENTE_LVL_4_2_DUCK,
    PARIENTE_LVL_4_2_JUMP,
    PARIENTE_LVL_4_2_WALKING_1,
    PARIENTE_LVL_4_2_WALKING_2,
    PARIENTE_LVL_4_2_WALKING_3,
    PASTEL,
    PIPE_BODY_STYLE_1,
    PIPE_BODY_STYLE_2,
    PIPE_BODY_STYLE_3,
    PIPE_BODY_STYLE_4,
    PIPE_BODY_STYLE_5,
    PIPE_HEAD_BIG,
    PIPE_HEAD_HORIZONTAL,
    PIPE_HEAD_SMALL,
    SMALL_BUSH,
    SMALL_CLOUD,
    SMALL_MOUNTAIN,
    SMALL_TREE,
    VALVOOPA_COMING_OUT_1,
    VALVOOPA_COMING_OUT_2,
    VALVOOPA_INSIDE,
    VALVOOPA_WALKING_1,
    VALVOOPA_WALKING_2,
    WALL_BLOCK,
)

heroes: Dict[HeroType, Dict[HeroLevel, Dict[HeroState, List[Surface]]]] = {
    HeroType.PARIENTE: {
        HeroLevel.NORMAL: {
            HeroState.IDLE: [PARIENTE_LVL_1],
            HeroState.RUN: [
                PARIENTE_LVL_1_WALKING_1,
                PARIENTE_LVL_1_WALKING_2,
                PARIENTE_LVL_1_WALKING_3,
            ],
            HeroState.JUMP: [PARIENTE_LVL_1_JUMP],
            HeroState.DOWN: [
                PARIENTE_LVL_1_DOWN_1,
                PARIENTE_LVL_1_DOWN_2,
            ],
            HeroState.BRAKE: [PARIENTE_LVL_1_BRAKE],
            HeroState.DEAD: [PARIENTE_LVL_1_DIED],
        },
        HeroLevel.BIG: {
            HeroState.IDLE: [PARIENTE_LVL_2],
            HeroState.RUN: [
                PARIENTE_LVL_2_WALKING_1,
                PARIENTE_LVL_2_WALKING_2,
                PARIENTE_LVL_2_WALKING_3,
            ],
            HeroState.JUMP: [PARIENTE_LVL_2_JUMP],
            HeroState.DUCK: [PARIENTE_LVL_2_DUCK],
            HeroState.BRAKE: [PARIENTE_LVL_2_BRAKE],
            HeroState.DOWN: [
                PARIENTE_LVL_2_DOWN_1,
                PARIENTE_LVL_2_DOWN_2,
            ],
        },
        HeroLevel.COCA: {
            HeroState.IDLE: [PARIENTE_LVL_3],
            HeroState.RUN: [
                PARIENTE_LVL_3_WALKING_1,
                PARIENTE_LVL_3_WALKING_2,
                PARIENTE_LVL_3_WALKING_3,
            ],
            HeroState.JUMP: [PARIENTE_LVL_3_JUMP],
            HeroState.DUCK: [PARIENTE_LVL_3_DUCK],
            HeroState.BRAKE: [PARIENTE_LVL_3_BRAKE],
            HeroState.DOWN: [
                PARIENTE_LVL_3_DOWN_1,
                PARIENTE_LVL_3_DOWN_2,
            ],
        },
        HeroLevel.BORRACHO_SMALL: {
            HeroState.IDLE: [PARIENTE_LVL_4_1],
            HeroState.RUN: [
                PARIENTE_LVL_4_1_WALKING_1,
                PARIENTE_LVL_4_1_WALKING_2,
                PARIENTE_LVL_4_1_WALKING_3,
            ],
            HeroState.JUMP: [PARIENTE_LVL_4_1_JUMP],
            HeroState.DOWN: [
                PARIENTE_LVL_4_1_DOWN_1,
                PARIENTE_LVL_4_1_DOWN_2,
            ],
            HeroState.BRAKE: [PARIENTE_LVL_4_1_BRAKE],
            HeroState.DEAD: [PARIENTE_LVL_4_1_DIED],
        },
        HeroLevel.BORRACHO_BIG: {
            HeroState.IDLE: [PARIENTE_LVL_4_2],
            HeroState.RUN: [
                PARIENTE_LVL_4_2_WALKING_1,
                PARIENTE_LVL_4_2_WALKING_2,
                PARIENTE_LVL_4_2_WALKING_3,
            ],
            HeroState.JUMP: [PARIENTE_LVL_4_2_JUMP],
            HeroState.DUCK: [PARIENTE_LVL_4_2_DUCK],
            HeroState.BRAKE: [PARIENTE_LVL_4_2_BRAKE],
            HeroState.DOWN: [
                PARIENTE_LVL_4_2_DOWN_1,
                PARIENTE_LVL_4_2_DOWN_2,
            ],
        },
    },
    HeroType.HIJITA: {
        HeroLevel.NORMAL: {
            HeroState.IDLE: [HIJITA_LVL_1],
            HeroState.RUN: [
                HIJITA_LVL_1_WALKING_1,
                HIJITA_LVL_1_WALKING_2,
                HIJITA_LVL_1_WALKING_3,
            ],
            HeroState.JUMP: [HIJITA_LVL_1_JUMP],
            HeroState.DOWN: [HIJITA_LVL_1_DOWN_1, HIJITA_LVL_1_DOWN_2],
            HeroState.BRAKE: [HIJITA_LVL_1_BRAKE],
            HeroState.DEAD: [HIJITA_LVL_1_DIED],
        },
        HeroLevel.BIG: {
            HeroState.IDLE: [HIJITA_LVL_2],
            HeroState.RUN: [
                HIJITA_LVL_2_WALKING_1,
                HIJITA_LVL_2_WALKING_2,
                HIJITA_LVL_2_WALKING_3,
            ],
            HeroState.JUMP: [HIJITA_LVL_2_JUMP],
            HeroState.DUCK: [HIJITA_LVL_2_DUCK],
            HeroState.BRAKE: [HIJITA_LVL_2_BRAKE],
            HeroState.DOWN: [HIJITA_LVL_2_DOWN_1, HIJITA_LVL_2_DOWN_2],
        },
        HeroLevel.COCA: {
            HeroState.IDLE: [HIJITA_LVL_3],
            HeroState.RUN: [
                HIJITA_LVL_3_WALKING_1,
                HIJITA_LVL_3_WALKING_2,
                HIJITA_LVL_3_WALKING_3,
            ],
            HeroState.JUMP: [HIJITA_LVL_3_JUMP],
            HeroState.DUCK: [HIJITA_LVL_3_DUCK],
            HeroState.BRAKE: [HIJITA_LVL_3_BRAKE],
            HeroState.DOWN: [HIJITA_LVL_3_DOWN_1, HIJITA_LVL_3_DOWN_2],
        },
        HeroLevel.BORRACHO_SMALL: {
            HeroState.IDLE: [HIJITA_LVL_4_1],
            HeroState.RUN: [
                HIJITA_LVL_4_1_WALKING_1,
                HIJITA_LVL_4_1_WALKING_2,
                HIJITA_LVL_4_1_WALKING_3,
            ],
            HeroState.JUMP: [HIJITA_LVL_4_1_JUMP],
            HeroState.DOWN: [
                HIJITA_LVL_4_1_DOWN_1,
                HIJITA_LVL_4_1_DOWN_2,
            ],
            HeroState.BRAKE: [HIJITA_LVL_4_1_BRAKE],
            HeroState.DEAD: [HIJITA_LVL_4_1_DIED],
        },
        HeroLevel.BORRACHO_BIG: {
            HeroState.IDLE: [HIJITA_LVL_4_2],
            HeroState.RUN: [
                HIJITA_LVL_4_2_WALKING_1,
                HIJITA_LVL_4_2_WALKING_2,
                HIJITA_LVL_4_2_WALKING_3,
            ],
            HeroState.JUMP: [HIJITA_LVL_4_2_JUMP],
            HeroState.DUCK: [HIJITA_LVL_4_2_DUCK],
            HeroState.BRAKE: [HIJITA_LVL_4_2_BRAKE],
            HeroState.DOWN: [
                HIJITA_LVL_4_2_DOWN_1,
                HIJITA_LVL_4_2_DOWN_2,
            ],
        },
    },
    HeroType.CUMPA: {
        HeroLevel.NORMAL: {
            HeroState.IDLE: [CUMPA_LVL_1],
            HeroState.RUN: [
                CUMPA_LVL_1_WALKING_1,
                CUMPA_LVL_1_WALKING_2,
                CUMPA_LVL_1_WALKING_3,
            ],
            HeroState.JUMP: [CUMPA_LVL_1_JUMP],
            HeroState.DOWN: [CUMPA_LVL_1_DOWN_1, CUMPA_LVL_1_DOWN_2],
            HeroState.BRAKE: [CUMPA_LVL_1_BRAKE],
            HeroState.DEAD: [CUMPA_LVL_1_DIED],
        },
        HeroLevel.BIG: {
            HeroState.IDLE: [CUMPA_LVL_2],
            HeroState.RUN: [
                CUMPA_LVL_2_WALKING_1,
                CUMPA_LVL_2_WALKING_2,
                CUMPA_LVL_2_WALKING_3,
            ],
            HeroState.JUMP: [CUMPA_LVL_2_JUMP],
            HeroState.DUCK: [CUMPA_LVL_2_DUCK],
            HeroState.BRAKE: [CUMPA_LVL_2_BRAKE],
            HeroState.DOWN: [CUMPA_LVL_2_DOWN_1, CUMPA_LVL_2_DOWN_2],
        },
        HeroLevel.COCA: {
            HeroState.IDLE: [CUMPA_LVL_3],
            HeroState.RUN: [
                CUMPA_LVL_3_WALKING_1,
                CUMPA_LVL_3_WALKING_2,
                CUMPA_LVL_3_WALKING_3,
            ],
            HeroState.JUMP: [CUMPA_LVL_3_JUMP],
            HeroState.DUCK: [CUMPA_LVL_3_DUCK],
            HeroState.BRAKE: [CUMPA_LVL_3_BRAKE],
            HeroState.DOWN: [CUMPA_LVL_3_DOWN_1, CUMPA_LVL_3_DOWN_2],
        },
        HeroLevel.BORRACHO_SMALL: {
            HeroState.IDLE: [CUMPA_LVL_4_1],
            HeroState.RUN: [
                CUMPA_LVL_4_1_WALKING_1,
                CUMPA_LVL_4_1_WALKING_2,
                CUMPA_LVL_4_1_WALKING_3,
            ],
            HeroState.JUMP: [CUMPA_LVL_4_1_JUMP],
            HeroState.DOWN: [
                CUMPA_LVL_4_1_DOWN_1,
                CUMPA_LVL_4_1_DOWN_2,
            ],
            HeroState.BRAKE: [CUMPA_LVL_4_1_BRAKE],
            HeroState.DEAD: [CUMPA_LVL_4_1_DIED],
        },
        HeroLevel.BORRACHO_BIG: {
            HeroState.IDLE: [CUMPA_LVL_4_2],
            HeroState.RUN: [
                CUMPA_LVL_4_2_WALKING_1,
                CUMPA_LVL_4_2_WALKING_2,
                CUMPA_LVL_4_2_WALKING_3,
            ],
            HeroState.JUMP: [CUMPA_LVL_4_2_JUMP],
            HeroState.DUCK: [CUMPA_LVL_4_2_DUCK],
            HeroState.BRAKE: [CUMPA_LVL_4_2_BRAKE],
            HeroState.DOWN: [
                CUMPA_LVL_4_2_DOWN_1,
                CUMPA_LVL_4_2_DOWN_2,
            ],
        },
    },
}


elements: Dict[ElementType, Dict[ElementSubType, List[Surface]]] = {
    ElementType.BLOCK: {
        ElementSubType.OVERWORLD_BLOCK: [OVERWORLD_BLOCK],
        ElementSubType.WALL_BLOCK: [WALL_BLOCK],
        ElementSubType.OVERWORLD_TERRAIN_BLOCK: [OVERWORLD_TERRAIN_BLOCK],
    },
    ElementType.MISTERY_BOX: {
        ElementSubType.DEFAULT_MISTERY_BOX: [
            MASTERY_BLOCK_1,
            MASTERY_BLOCK_2,
            MASTERY_BLOCK_3,
        ]
    },
    ElementType.PIPE: {
        ElementSubType.PIPE_HEAD_SMALL: [PIPE_HEAD_SMALL],
        ElementSubType.PIPE_HEAD_BIG: [PIPE_HEAD_BIG],
        ElementSubType.PIPE_HEAD_HORIZONTAL: [PIPE_HEAD_HORIZONTAL],
        ElementSubType.PIPE_BODY_STYLE_1: [PIPE_BODY_STYLE_1],
        ElementSubType.PIPE_BODY_STYLE_2: [PIPE_BODY_STYLE_2],
        ElementSubType.PIPE_BODY_STYLE_3: [PIPE_BODY_STYLE_3],
        ElementSubType.PIPE_BODY_STYLE_4: [PIPE_BODY_STYLE_4],
        ElementSubType.PIPE_BODY_STYLE_5: [PIPE_BODY_STYLE_5],
    },
    ElementType.CLOUD: {
        ElementSubType.SMALL_CLOUD: [SMALL_CLOUD],
        ElementSubType.MEDIUM_CLOUD: [MEDIUM_CLOUD],
        ElementSubType.BIG_CLOUD: [BIG_CLOUD],
    },
    ElementType.BUSH: {
        ElementSubType.SMALL_BUSH: [SMALL_BUSH],
        ElementSubType.MEDIUM_BUSH: [MEDIUM_BUSH],
        ElementSubType.BIG_BUSH: [BIG_BUSH],
    },
    ElementType.MOUNTAIN: {
        ElementSubType.SMALL_MOUNTAIN: [SMALL_MOUNTAIN],
        ElementSubType.MEDIUM_MOUNTAIN: [MEDIUM_MOUNTAIN],
        ElementSubType.BIG_MOUNTAIN: [BIG_MOUNTAIN],
    },
    ElementType.TREE: {
        ElementSubType.SMALL_TREE: [SMALL_TREE],
        ElementSubType.MEDIUM_TREE: [MEDIUM_TREE],
        ElementSubType.BIG_TREE: [BIG_TREE],
    },
    ElementType.CASTLE: {ElementSubType.DEFAULT_CASTLE: [CASTLE]},
    ElementType.FLAG: {
        ElementSubType.FLAG_PIPE: [FLAG_PIPE],
        ElementSubType.FLAG_WIN: [FLAG_WIN],
        ElementSubType.FLAG_SUPPORT: [FLAG_SUPPORT],
        ElementSubType.FLAG_LIMITER: [FLAG_LIMITER],
    },
    ElementType.COIN: {
        ElementSubType.COIN: [COIN_1, COIN_2, COIN_3, COIN_4],
    },
    ElementType.COIN_ICON: {
        ElementSubType.COIN_ICON: [COIN_ICON_1, COIN_ICON_2, COIN_ICON_3],
    },
}

enemies: Dict[EnemyType, Dict[EnemyState, List[Surface]]] = {
    EnemyType.VALVOOPA: {
        EnemyState.WALKING: [VALVOOPA_WALKING_1, VALVOOPA_WALKING_2],
        EnemyState.COMING_OUT: [VALVOOPA_COMING_OUT_1, VALVOOPA_COMING_OUT_2],
        EnemyState.DEAD: [VALVOOPA_INSIDE],
    },
    EnemyType.EVOOMBA: {
        EnemyState.WALKING: [EVOOMBA_WALKING_1, EVOOMBA_WALKING_2],
        EnemyState.DEAD: [EVOOMBA_DIED],
    },
}

power_ups: Dict[PowerUpType, List[Surface]] = {
    PowerUpType.PASTEL: [PASTEL],
    PowerUpType.CAIMAN: [ALCOHOL_CAIMAN],
    PowerUpType.COCA: [COCA_PLANT_1, COCA_PLANT_2],
}
