from .final import FINAL_CINEMATIC_AUDIO, FINAL_CINEMATIC_VIDEO

from .victory import (
    VICTORY_CINEMATIC_NORMAL_VIDEO,
    VICTORY_CINEMATIC_ONE_FIREWORK_AUDIO,
    VICTORY_CINEMATIC_ONE_FIREWORK_VIDEO,
    VICTORY_CINEMATIC_THREE_FIREWORKS_AUDIO,
    VICTORY_CINEMATIC_THREE_FIREWORKS_VIDEO,
    VICTORY_CINEMATIC_SIX_FIREWORKS_AUDIO,
    VICTORY_CINEMATIC_SIX_FIREWORKS_VIDEO,
)

__all__ = [
    "FINAL_CINEMATIC_AUDIO",
    "FINAL_CINEMATIC_VIDEO",
    "VICTORY_CINEMATIC_NORMAL_VIDEO",
    "VICTORY_CINEMATIC_ONE_FIREWORK_AUDIO",
    "VICTORY_CINEMATIC_ONE_FIREWORK_VIDEO",
    "VICTORY_CINEMATIC_THREE_FIREWORKS_AUDIO",
    "VICTORY_CINEMATIC_THREE_FIREWORKS_VIDEO",
    "VICTORY_CINEMATIC_SIX_FIREWORKS_AUDIO",
    "VICTORY_CINEMATIC_SIX_FIREWORKS_VIDEO",
]
