from ...directories import (
    VICTORY_CINEMATIC_AUDIO_DIR,
    VICTORY_CINEMATIC_VIDEO_DIR,
)

VICTORY_CINEMATIC_ONE_FIREWORK_VIDEO = (
    VICTORY_CINEMATIC_VIDEO_DIR + "final_one_firework.mp4"
)
VICTORY_CINEMATIC_ONE_FIREWORK_AUDIO = (
    VICTORY_CINEMATIC_AUDIO_DIR + "final_one_firework.mp3"
)

VICTORY_CINEMATIC_THREE_FIREWORKS_VIDEO = (
    VICTORY_CINEMATIC_VIDEO_DIR + "final_three_fireworks.mp4"
)
VICTORY_CINEMATIC_THREE_FIREWORKS_AUDIO = (
    VICTORY_CINEMATIC_AUDIO_DIR + "final_three_fireworks.mp3"
)

VICTORY_CINEMATIC_SIX_FIREWORKS_VIDEO = (
    VICTORY_CINEMATIC_VIDEO_DIR + "final_six_fireworks.mp4"
)
VICTORY_CINEMATIC_SIX_FIREWORKS_AUDIO = (
    VICTORY_CINEMATIC_AUDIO_DIR + "final_six_fireworks.mp3"
)
